name: Bump minor version

on:
  workflow_dispatch:

jobs:
  bump-minor:
    if: github.ref == 'refs/heads/main'
    name: Bump minor version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "v@vadzim.info"

      - name: Bump minor version
        run: |
          npm version minor

      - name: Pushing changes
        run: |
          git push origin HEAD --tags
